services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  admin.settings:
      class: AdminBundle\Service\settings
      arguments: [ "@doctrine.orm.entity_manager"]