<?php

namespace AppBundle\Repository;

/**
 * blogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blogPostRepository extends \Doctrine\ORM\EntityRepository
{
}
