<?php

namespace AppBundle\Repository;

/**
 * factorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class factorRepository extends \Doctrine\ORM\EntityRepository
{
}
