<?php

namespace AppBundle\Repository;

/**
 * personalDicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personalDicRepository extends \Doctrine\ORM\EntityRepository
{
}
