<?php

namespace AppBundle\Repository;

/**
 * qesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qesRepository extends \Doctrine\ORM\EntityRepository
{
}
