<?php

namespace AppBundle\Repository;

/**
 * transLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class transLangRepository extends \Doctrine\ORM\EntityRepository
{
}
