<?php

namespace AppBundle\Repository;

/**
 * userOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
