payment:
    resource: "@paymentBundle/Controller/"
    type:     annotation
    prefix:   /

spage:
    resource: "@spageBundle/Controller/"
    type:     annotation
    prefix:   /

grid:
    resource: "@gridBundle/Controller/"
    type:     annotation
    prefix:   /

entity_manager:
    resource: "@entityManagerBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

date:
    resource: "@DateBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

