<?php

namespace AdminBundle\Repository;

/**
 * settingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class settingRepository extends \Doctrine\ORM\EntityRepository
{
}
