services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     user.mgr:
        class: UserBundle\Service\Manage
        arguments: [ "@doctrine.orm.entity_manager","@form.factory" ]
