<?php

namespace paymentBundle\Repository;

/**
 * gatewaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gatewaysRepository extends \Doctrine\ORM\EntityRepository
{
}
